#!/bin/bash

dir_to_backup="$1"
backup_folder="$2"

if [ -z "$dir_to_backup" ]
then
    echo "Please supply folder to be backed up"
    exit 0
fi

if [ ! -d "$dir_to_backup" ]
then
    echo "Folder $dir_to_backup doesn't exit, Please supply an existing folder to be backed up"
    exit 0
fi

if [ -z "$backup_folder" ] || [ ! -d "$backup_folder" ]
then
    mkdir $HOME/Backup
    backup_folder=$HOME/Backup
    echo "This is $backup_folder folder"
fi

rsync -avz $dir_to_backup $backup_folderls