#!/bin/bash

#echo `git status`
git status | grep Untracked
if [ $? -ne 0 ]
then
    echo "No files to add."
    read -p "Please enter filename or . to add all files: " file
    git add "$file"
fi

read -p "Please enter your commit message: " message

git commit -m "$message"
git push
