#!/bin/bash

showHelp()
{
    echo "Script usage: search_file [-in] [-pn] file"
    echo "Use -i to ignore case. The -n to show the line numbers of the matched lines.\
     The -pn flag is used to set the number of lines shown when using more."
}

flag="-"

while getopts "inp:" option
do
    if [ "$option" == "i" ]
    then
        echo $option is an option
        flag=$flag"i"
    elif [ "$option" == "n" ]
    then
        echo $option is an option
        flag=$flag"n"
    elif [ "$option" == "p" ]
    then
        echo Got option $option in $OPTARG $OPTIND
        pvalue="$OPTARG"
        #flag="-m$pvalue"
        moreFlag="| more -$pvalue"
    else
        showHelp
        exit 1
    fi
done
shift "$(($OPTIND -1))"
file=$1

read -p "Please enter string to look for: " string
#grep "$flag" "$string" "$file"
while [ -n "$string" ]
do
    command="grep $flag $string $file"
    #command="grep $flag $string $file $moreFlag"
    echo ran command: $command
    $command
    read -p "Please enter string to look for: " string
done