#!/bin/bash

st=$1
task=$2
user=`logname`
echo USER: $user

if [ "$st" != "start" ] && [ "$st" != "stop" ]
then
    echo "Please enter start or stop"

else
    if [ "$st" = "start" ]
    then
        echo "Start tracking time"
        export startTime=`date +%s`
    else

        echo "Stop tracking time"
        echo "Start time: $startTime"
    
        stopTime=`date +%s`
        echo "Stop time: $stopTime"
        if [ "$startTime" -gt 0 ]
        then
            timeSpent=$(( $stopTime - $startTime ))
            echo $timeSpent
            startTime=0
        else
            echo "There is no task to stop"       
        fi
    fi
fi

