#!/bin/bash

user=`logname`
echo USER: $user
#input=`read -p "How many courses are you taking: "`

while read -p "Enter course:  "; 
do 
    echo -n  "How many hours do you spend on this course: "
    read count
    echo "$REPLY" : $count hours
done
