#!/bin/bash

awk -v SEARCH="$1" '
BEGIN {
    #print "Search for <" SEARCH">"
    COUNT = 0
}
function addLine(line)
{
    line = NR " " line
    if (prevLine == "" )
        prevLine = line
    else if (lineToCheck == "" )
    {
        lineToCheck = line
        LINE_TO_CHECK_NR = NR
    }    
    else if (nextLine == "" )
        nextLine = line
    else
    {
        prevLine = lineToCheck
        lineToCheck = nextLine
        nextLine = line
        LINE_TO_CHECK_NR = NR-1
    }
}
function printWindow()
{
    if (prevLine != "")
        print "---  " prevLine
    if (lineToCheck != "")
        print "---> " lineToCheck
    if (nextLine != "")
        print "---  " nextLine
    print "" 
}
function printIfMatch()
{
    #Handles special case on the first line
    if (nextLine == "" && prevLine ~ SEARCH && lineToCheck != "")
    {
        print "Found: " SEARCH" on line 1" 
        print ""
        print "---> " prevLine
        print "---  " lineToCheck
        print ""
        COUNT++
        return 1
    }
    if (nextLine == "")
        return 1

    if (lineToCheck ~ SEARCH)
    {
        print "Found: " SEARCH" on line " LINE_TO_CHECK_NR
        print ""
        printWindow()
        COUNT++
        return 1 
    }
}
{
    addLine($0)
    printIfMatch()

}
END {
    if ($0 ~ SEARCH)
    {
        print "Found: " SEARCH" on line " NR
        addLine("")
        nextLine=""
        printWindow()
        COUNT++
    }
    print "----------------"
    print "Summary: "
    print "----------------"
    print "found: " SEARCH" "  COUNT" times "
}'
