#	Makefile for HW5

#	Written by: Mubarak Mikail April 23, 2020.

MAKE 	=	make

MAKEFLAGS = -f

FILES = programs.mak arrays.mak random.mak
# Specify the source with main and the executable file name

#all: ${FILES}
all: programs.mak arrays.mak random.mak

# ${FILES}:
# 	 ${MAKE} ${MAKEFLAGS} $@
programs.mak:
	 ${MAKE} -f $@

clean:
 