#	Makefile for HW5

#	Written by: Mubarak Mikail April 23, 2020.

MAKE 	=	make

# Specify the source with main and the executable file name

all: 
	 ${MAKE} -f programs.mak
	 ${MAKE} -f arrays.mak; \
	 ${MAKE} -f random.mak

clean:
 
